### ISSUE TITLE
How to change uppercase to lowercase

### ISSUE THREAD

**Issue by charan-web** [EddieJaoudeCommunity/awesome-github-profiles#120]
hey im new here. i already pull a request to this repo.but it got rejected by eddie sir due to uppercase letter. thats why im writing this in lower case. can anyone help me out from this . i need to change my pull request title upper case letters to lowercase.

**Comment by charan-web** [comment]
sorry i just saw the edit button.

**Comment by eddiejaoude** [comment]
Your PR did not get rejected, it is still open and waiting for you to make the changes. 

You can make code changes in your fork in the same branch and it will be appended to your open PR #96
