### ISSUE TITLE
Can I join the community? I would like to work with u all

### ISSUE THREAD

**Issue by carlosdeque-s** [EddieJaoudeCommunity/awesome-github-profiles#132]
Hi I'm new at github and my experience with code is from the last 2 years with some months of innactivity in between.

Is there any task I could do or somethings I need to learn if I only have a small experience in Js, Ruby, Java, C++, Python?

Feel free to ask me from email if you have some suggestions or projects I could help you with - al386762@uji.es

**Comment by eddiejaoude** [comment]
**Invitation sent for the GitHub Organisation. Welcome to the community** 🎉

Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see, you can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/EddieJaoudeCommunity/people

Tips for practising:

Customise your GitHub profile, here is a live stream on it https://www.youtube.com/watch?v=cT6GXCuS0Zo
Practice repo, instructions on how to add your name to the README in the README https://github.com/EddieJaoudeCommunity/hacktoberfest-practice
Remember contributing to open source is not just about code, its about collaboration, communication and adding value

I hope that helps
