### ISSUE TITLE
Arwaz Khan

### ISSUE THREAD

**Issue by arwazkhan189** [EddieJaoudeCommunity/awesome-github-profiles#147]
![Arwazkhan](https://user-images.githubusercontent.com/48387278/96334933-121b9800-1092-11eb-8904-a88502c8b003.png)

**Comment by arwazkhan189** [comment]
sir @eddiejaoude  please check PR #150

**Comment by eddiejaoude** [comment]
@arwazkhan189 I think the community has reviewed it already and left you some comments. Just some small tweaks, then it can be merged 👍
