### ISSUE TITLE
Reshaping my GitHub profile

### ISSUE THREAD

**Issue by EugeneGohh** [EddieJaoudeCommunity/awesome-github-profiles#162]
Anyone interested to work together? I wanna reshape my GitHub profile. (ps I am a beginner willing to learn from Open Source.)

**Comment by BOLT04** [comment]
Hi @EugeneGohh 😃, are you interested in working in any of the repositories of this organization? If you don't have a project that you like, try to pitch your idea for a new project on Discord, and see if more people like it 👍

**Comment by eddiejaoude** [comment]
@EugeneGohh in addition to what @BOLT04 mentioned. Have you looked at the examples in this repo? Your GitHub profile looks great, but if you want more ideas or inspiration, have a look at the README in this project - it has lots of examples
