### ISSUE TITLE
JSONLinting

### ISSUE THREAD

**Issue by stemount** [EddieJaoudeCommunity/awesome-github-profiles#173]
Following on from #171 Let's JSON Lint

**Acceptance Criteria** to put something in CI/CD pipelines that lints pull requests and throws out those that aren't
1. CI/CD pipeline will provide GitHub user with useful feedback of what line broke allowing folks to understand what went pete tong
1. CI/CD pipeline will provide GitHub user with useful feedback if the JSON is totally valid ⭐

**Comment by eddiejaoude** [comment]
Could we use Prettier in the project and as a GitHub Action https://github.com/marketplace/actions/prettier-action ?

**Comment by stemount** [comment]
@eddiejaoude for sure, totally gonna PR this as I wanna see it in action!

**Comment by stemount** [comment]
Good suggestion @eddiejaoude thanks for the PR approval.

For anyone else on the internets who lands on this, the `prettier-action` github page needs updating to suggest the latest version, I had to bump it up from `version:3.0` to `version:3.1` so that `only_changed` was not an unknown variable.

**Comment by stemount** [comment]
#175 to enhance this work
