### ISSUE TITLE
The Json file needs to be formatted correctly

### ISSUE THREAD

**Issue by varlackc** [EddieJaoudeCommunity/awesome-github-profiles#176]
The data.json file needs to be formated correctly

**Comment by stemount** [comment]
True, @frankiefab100's PR does this on #172 and #175 actually adds a Prettier JSON/MD checker as a GitHub action.

Can you/I close this issue based upon this work? You may need to pull from upstream.

**Comment by frankiefab100** [comment]
@varlackc issue has been resolved and #172 closed
