### ISSUE TITLE
Ivan Pesenti

### ISSUE THREAD

**Issue by ivan-pesenti** [EddieJaoudeCommunity/awesome-github-profiles#204]
![github-profile-screenshot](https://user-images.githubusercontent.com/60645922/103266518-0ad90a80-49b0-11eb-81ff-5dac7e47a255.png)

**Comment by ivan-pesenti** [comment]
I'm going to open another one soon

**Comment by eddiejaoude** [comment]
Sure 👍 . Any questions let us know 🤓
