### ISSUE TITLE
README Update Action Runs on forks

### ISSUE THREAD

**Issue by AllanRegush** [EddieJaoudeCommunity/awesome-github-profiles#264]
add if statement to yaml so the action only runs on our Repo
Action file location: .github/workflows/main.yml
```yml
if: github.repository_owner == 'EddieJaoudeCommunity'
```

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

**Comment by eddiejaoude** [comment]
Thanks 👍
