### ISSUE TITLE
Issue in github actions

### ISSUE THREAD

**Issue by aniketsingh98571** [EddieJaoudeCommunity/awesome-github-profiles#90]
replace eddiejaoude with eddiejaoudecommunity.

**Comment by eddiejaoude** [comment]
The GitHub Action has moved and the usage is out of date.

```diff
- uses: eddiejaoude/github-actions-reader-writer@v0.1
+ uses: eddiejaoudecommunity/gh-actions-html-table-generator@v0.1
```

https://github.com/EddieJaoudeCommunity/awesome-github-profiles/blob/main/.github/workflows/main.yml#L10
